#version 450

layout(local_size_x = 256) in;

layout(set = 0, binding = 0, std430) readonly buffer Src {
  uint data[];
} src_buf;

layout(set = 0, binding = 1, std430) readonly buffer Indices {
  int data[];
} indices_buf;

layout(set = 0, binding = 2, std430) writeonly buffer Dst {
  uint data[];
} dst_buf;

void main() {
  uint i = gl_GlobalInvocationID.x;
  if (i >= indices_buf.data.length()) {
    return;
  }
  int index = indices_buf.data[i];
  uint src_index = uint(index);
  if (index < 0 || src_index >= src_buf.data.length()) {
    dst_buf.data[i] = 0u;
    return;
  }
  dst_buf.data[i] = src_buf.data[src_index];
}
