#version 450

layout(local_size_x = 256) in;

#ifndef VALUE_KIND
#define VALUE_KIND 0
#endif

#if VALUE_KIND == 3 || VALUE_KIND == 4
#extension GL_ARB_gpu_shader_int64 : require
#elif VALUE_KIND == 5
#extension GL_ARB_gpu_shader_fp64 : require
#endif

#if VALUE_KIND == 1
#define VALUE_T float
#elif VALUE_KIND == 2
#define VALUE_T uint
#elif VALUE_KIND == 3
#define VALUE_T uint64_t
#elif VALUE_KIND == 4
#define VALUE_T int64_t
#elif VALUE_KIND == 5
#define VALUE_T double
#else
#define VALUE_T int
#endif

layout(set = 0, binding = 0, std430) buffer Data {
  VALUE_T data[];
} data_buf;

layout(set = 0, binding = 1, std430) readonly buffer BlockOffsets {
  VALUE_T data[];
} block_offsets;

void main() {
  uint idx = gl_GlobalInvocationID.x;
  uint n = data_buf.data.length();
  if (idx >= n) {
    return;
  }

  uint block = idx / 256u;
  if (block > 0u) {
    data_buf.data[idx] += block_offsets.data[block - 1u];
  }
}
