#version 450

layout(local_size_x = 256) in;

layout(set = 0, binding = 0, std430) buffer Data {
  int data[];
} data_buf;

layout(set = 0, binding = 1, std430) readonly buffer BlockOffsets {
  int data[];
} block_offsets;

void main() {
  uint idx = gl_GlobalInvocationID.x;
  uint n = data_buf.data.length();
  if (idx >= n) {
    return;
  }

  uint block = idx / 256u;
  if (block > 0u) {
    data_buf.data[idx] += block_offsets.data[block - 1u];
  }
}
