#version 450

layout(local_size_x = 256) in;

layout(set = 0, binding = 0, std430) readonly buffer Src {
  int data[];
} src_buf;

layout(set = 0, binding = 1, std430) readonly buffer Indices {
  int data[];
} indices_buf;

layout(set = 0, binding = 2, std430) buffer Dst {
  int data[];
} dst_buf;

void main() {
  uint i = gl_GlobalInvocationID.x;
  if (i >= src_buf.data.length()) {
    return;
  }
  int index = indices_buf.data[i];
  uint dst_index = uint(index);
  if (index < 0 || dst_index >= dst_buf.data.length()) {
    return;
  }
  atomicAdd(dst_buf.data[dst_index], src_buf.data[i]);
}
