#version 450

#ifndef VALUE_KIND
#define VALUE_KIND 0
#endif

#if VALUE_KIND == 1
#extension GL_EXT_shader_atomic_float : require
#define VALUE_T float
#elif VALUE_KIND == 2
#define VALUE_T uint
#elif VALUE_KIND == 3
#extension GL_ARB_gpu_shader_int64 : require
#extension GL_EXT_shader_atomic_int64 : require
#define VALUE_T uint64_t
#elif VALUE_KIND == 4
#extension GL_ARB_gpu_shader_int64 : require
#extension GL_EXT_shader_atomic_int64 : require
#define VALUE_T int64_t
#elif VALUE_KIND == 5
#extension GL_ARB_gpu_shader_fp64 : require
#extension GL_EXT_shader_atomic_float : require
#define VALUE_T double
#else
#define VALUE_T int
#endif

layout(local_size_x = 256) in;

layout(set = 0, binding = 0, std430) readonly buffer Src {
  VALUE_T data[];
} src_buf;

layout(set = 0, binding = 1, std430) readonly buffer Indices {
  int data[];
} indices_buf;

layout(set = 0, binding = 2, std430) buffer Dst {
  VALUE_T data[];
} dst_buf;

void main() {
  uint i = gl_GlobalInvocationID.x;
  if (i >= src_buf.data.length()) {
    return;
  }
  int index = indices_buf.data[i];
  uint dst_index = uint(index);
  if (index < 0 || dst_index >= dst_buf.data.length()) {
    return;
  }
  atomicAdd(dst_buf.data[dst_index], src_buf.data[i]);
}
