#version 450

layout(local_size_x = 256) in;
layout(set = 0, binding = 0, std430) readonly buffer SolutionDirection { float data[]; } solution_direction_buf;
layout(set = 0, binding = 1, std430) readonly buffer SolutionIntermediate { float data[]; } solution_intermediate_buf;
layout(set = 0, binding = 2, std430) readonly buffer Intermediate { float data[]; } intermediate_buf;
layout(set = 0, binding = 3, std430) readonly buffer OperatorIntermediate { float data[]; } operator_intermediate_buf;
layout(set = 0, binding = 4, std430) buffer Solution { float data[]; } solution_buf;
layout(set = 0, binding = 5, std430) buffer Residual { float data[]; } residual_buf;
layout(set = 0, binding = 6, std430) readonly buffer State { uint data[]; } state_buf;
layout(push_constant) uniform Params { uint n; uint unused0; uint unused1; uint unused2; } params;

void main() {
  uint stride = gl_NumWorkGroups.x * gl_WorkGroupSize.x;
  uint index = gl_GlobalInvocationID.x;
  if (int(state_buf.data[19]) == 0) return;
  float alpha = uintBitsToFloat(state_buf.data[1]);
  float omega = uintBitsToFloat(state_buf.data[2]);
  while (index < params.n) {
    solution_buf.data[index] += alpha * solution_direction_buf.data[index] +
                                omega * solution_intermediate_buf.data[index];
    residual_buf.data[index] = intermediate_buf.data[index] -
                               omega * operator_intermediate_buf.data[index];
    if (params.n - index <= stride) break;
    index += stride;
  }
}
