#version 450

layout(local_size_x = 256) in;

layout(set = 0, binding = 0, std430) readonly buffer Src {
  int data[];
} src_buf;

layout(set = 0, binding = 1, std430) writeonly buffer Dst {
  int data[];
} dst_buf;

layout(set = 0, binding = 2, std430) readonly buffer Params {
  uint scale;
  uint bias;
} params;

void main() {
  uint i = gl_GlobalInvocationID.x;
  if (i >= src_buf.data.length()) {
    return;
  }
  uint value = uint(src_buf.data[i]);
  dst_buf.data[i] = int(value * params.scale + params.bias);
}
