#pragma once
#include "taichi/ir/ir.h"

namespace taichi::lang {

// BasicStmtVisitor — visits all non-container statements.
//
// IMPORTANT default-dispatch pitfall (read before subclassing):
//
//   The base ctor (basic_stmt_visitor.cpp) sets only:
//       allow_undefined_visitor = true;
//   It DOES NOT set:
//       invoke_default_visitor  = true;
//
//   That means typed visitors (visit(MatrixInitStmt*), visit(AllocaStmt*),
//   ...) generated by the DEFINE_VISIT macro will short-circuit silently for
//   any Stmt subclass that does not have a dedicated override in the concrete
//   IRVisitor subclass. In particular, if you write a "predicate visitor"
//   that only overrides `visit(Stmt *stmt)` expecting it to fire for every
//   statement, that override WILL NEVER BE CALLED for any typed Stmt — your
//   pass appears to work on scalar-only test inputs by accident.
//
//   Two correct ways to write a visitor that inspects every Stmt:
//
//     (a) In your subclass ctor, explicitly opt in:
//             MyVisitor() { invoke_default_visitor = true; }
//
//     (b) Provide typed-visitor overrides for every Stmt class you care
//         about (a closed set; preferred when you need typed access).
//
// See: taichi/ir/ir.h DEFINE_VISIT macro, basic_stmt_visitor.cpp ctor,
//      transforms/scalarize.cpp HasMatrixStmt.
class BasicStmtVisitor : public IRVisitor {
 public:
  BasicStmtVisitor();

  virtual void preprocess_container_stmt(Stmt *stmt) {
  }

  void visit(Block *stmt_list) override;

  void visit(IfStmt *if_stmt) override;

  void visit(WhileStmt *stmt) override;

  void visit(RangeForStmt *for_stmt) override;

  void visit(StructForStmt *for_stmt) override;

  void visit(MeshForStmt *for_stmt) override;

  void visit(OffloadedStmt *stmt) override;

  void visit(FrontendWhileStmt *stmt) override;

  void visit(FrontendForStmt *stmt) override;

  void visit(FrontendIfStmt *stmt) override;
};

}  // namespace taichi::lang
