"""Hardware capability contracts and provider-independent introspection."""

from taichi_forge.hardware import matrix, raster

from taichi_forge.hardware._capabilities import (
    DEPENDENCY_TIERS,
    DISCOVERY_STATES,
    ENABLEMENT_STATES,
    EXECUTION_CLASSES,
    EXECUTION_KINDS,
    FAILURE_SCOPES,
    GRAPH_SUPPORT_MODES,
    HARDWARE_ACCELERATION_LEVELS,
    HARDWARE_CAPABILITY_SCHEMA_VERSION,
    IMPLEMENTATION_STATUSES,
    LIFETIME_POLICIES,
    LOAD_MODES,
    OPERATION_SCOPES,
    PROVIDER_CLASSES,
    SELECTION_STATES,
    STREAM_BINDINGS,
    UPDATE_POLICIES,
    WORKSPACE_OWNERSHIP,
    HardwareCapabilityReport,
    HardwareOperationDescriptor,
    HardwareProviderDescriptor,
    ResolvedHardwareOperation,
    capability,
    operations,
    probe,
    providers,
    report,
)

__all__ = [
    "DEPENDENCY_TIERS",
    "DISCOVERY_STATES",
    "ENABLEMENT_STATES",
    "EXECUTION_CLASSES",
    "EXECUTION_KINDS",
    "FAILURE_SCOPES",
    "GRAPH_SUPPORT_MODES",
    "HARDWARE_ACCELERATION_LEVELS",
    "HARDWARE_CAPABILITY_SCHEMA_VERSION",
    "HardwareCapabilityReport",
    "HardwareOperationDescriptor",
    "HardwareProviderDescriptor",
    "IMPLEMENTATION_STATUSES",
    "LIFETIME_POLICIES",
    "LOAD_MODES",
    "OPERATION_SCOPES",
    "PROVIDER_CLASSES",
    "ResolvedHardwareOperation",
    "SELECTION_STATES",
    "STREAM_BINDINGS",
    "UPDATE_POLICIES",
    "WORKSPACE_OWNERSHIP",
    "capability",
    "operations",
    "probe",
    "providers",
    "report",
    "matrix",
    "raster",
]
