"""External D1 provider capability catalog fragments."""


def d1_provider_operations(_operation):
    return (
        _operation(
            "linalg.gemm.cublas",
            "linalg.gemm",
            "cublas",
            ("cuda",),
            "lazy_external",
            "vendor_algorithm",
            "vendor_library",
            "implementation_defined",
            ("python", "graph"),
            "external_library",
            "root_ordered",
            "explicit",
            "none",
            "existing_public",
            activation_mode="explicit_hardware_api",
            dependency_name="cuBLAS",
            resource_effects=("read:inputs", "read_write:output"),
            lifetime_policy="runtime_generation",
            update_policy="per_dispatch",
            requirements=("compatible cuBLAS shared library",),
            public_api="ti.hardware.linalg.gemm_f32",
            dtypes=("input:f32", "output:f32"),
            layouts=("compact row-major 2D",),
            numeric_contracts=("C = alpha * A @ B + beta * C",),
            notes=(
                "Explicit Python or root-Graph vendor-library command.",
                "The first execution lazy-loads the user's compatible cuBLAS shared library and retains one handle per Program.",
                "Ordinary matrix multiplication and Taichi kernels are never rewritten to call this provider.",
            ),
        ),
        _operation(
            "linalg.spmv.cusparse",
            "linalg.spmv",
            "cusparse",
            ("cuda",),
            "lazy_external",
            "vendor_algorithm",
            "vendor_library",
            "implementation_defined",
            ("python",),
            "external_library",
            "unsupported",
            "runtime_ordered",
            "provider_owned",
            "existing_public",
            activation_mode="domain_api_auto_provider",
            dependency_name="cuSPARSE",
            resource_effects=("read:sparse_matrix", "read:input", "write:output"),
            lifetime_policy="resource_generation",
            update_policy="rebind",
            requirements=("compatible cuSPARSE shared library",),
            public_api=("ti.linalg.SparseMatrix.spmv / set_provider_profile"),
            dtypes=("matrix:f32", "input:f32", "output:f32"),
            layouts=("scalar CSR", "fixed-block BSR when provider supports it"),
            numeric_contracts=("output = sparse_matrix @ input",),
            notes=(
                "The public sparse-matrix domain API considers cuSPARSE automatically on CUDA; users do not call a ti.hardware command.",
                "Without stable matrix-scoped cost evidence, auto fails closed to the embedded CUDA CSR/BSR kernel route.",
                "Validated evidence is loaded from the Forge fresh-process qualification artifact; handwritten timing fields are not accepted.",
                "Admission matches the exact sparse-topology fingerprint, device UUID, Forge runtime build, provider ABI/version, reuse, transfer/conversion cost, sample count, CV, and order drift.",
                "CSR SpMV caches matrix/vector descriptors, workspace, and optional provider preprocessing for repeated calls.",
                "The current stored SparseMatrix route is direct Python execution and is not a recordable Graph action.",
            ),
        ),
        _operation(
            "linalg.spmv.cusparse_explicit",
            "linalg.spmv",
            "cusparse",
            ("cuda",),
            "lazy_external",
            "vendor_algorithm",
            "vendor_library",
            "implementation_defined",
            ("python", "graph"),
            "external_library",
            "root_ordered",
            "runtime_ordered",
            "provider_owned",
            "existing_public",
            activation_mode="explicit_hardware_api",
            dependency_name="cuSPARSE",
            resource_effects=("read:sparse_matrix", "read:input", "write:output"),
            lifetime_policy="resource_generation",
            update_policy="rebind",
            requirements=("compatible cuSPARSE shared library",),
            public_api="ti.hardware.linalg.spmv_f32",
            dtypes=("matrix:f32", "input:f32", "output:f32"),
            layouts=("scalar CSR", "fixed-block BSR when provider supports it"),
            numeric_contracts=("output = sparse_matrix @ input",),
            notes=(
                "Explicit Python or root-Graph command over an existing CUDA SparseMatrix.",
                "The recording holds the matrix generation alive and reuses its cuSPARSE handle, descriptors, workspace, and optional preprocessing.",
                "This manual hardware interface is separate from the automatic SparseMatrix @ ndarray domain route.",
            ),
        ),
        _operation(
            "fft.transform.cufft",
            "fft.transform",
            "cufft",
            ("cuda",),
            "lazy_external",
            "vendor_algorithm",
            "vendor_library",
            "implementation_defined",
            ("python", "graph"),
            "external_library",
            "root_ordered",
            "runtime_ordered",
            "provider_owned",
            "existing_public",
            activation_mode="explicit_hardware_api",
            dependency_name="cuFFT",
            resource_effects=("read:input", "write:output", "write:workspace"),
            lifetime_policy="provider_plan",
            update_policy="rebind",
            requirements=("compatible cuFFT shared library",),
            public_api="ti.hardware.fft.CufftPlan1D / CufftPlanND",
            dtypes=("real:f32", "complex-pair:f32"),
            shapes_or_tiles=(
                "C2C:(length,2) or (batch,length,2)",
                "R2C:real length to Hermitian length//2+1",
                "C2R:Hermitian length//2+1 to real length",
                "CufftPlanND:batched rank-2/rank-3",
            ),
            layouts=(
                "compact out-of-place C2C/R2C/C2R",
                "explicit embed/element-stride/batch-distance",
            ),
            numeric_contracts=(
                "forward sign:-1",
                "inverse sign:+1 unnormalized",
                "inverse_scale:1/length",
            ),
            notes=(
                "Callbacks, LTO, multi-GPU, and independently arbitrary per-axis strides are excluded.",
                "Identical plan descriptors reuse a runtime-generation cuFFT plan; workspace bytes are queried from cuFFT.",
                "Discovery verifies the operation symbol contract only; transitive provider dependencies and workspace allocation are qualified when the first plan is created.",
            ),
        ),
        _operation(
            "linalg.solve.cudss",
            "linalg.sparse_direct_solve",
            "cudss",
            ("cuda",),
            "lazy_external",
            "vendor_algorithm",
            "vendor_library",
            "implementation_defined",
            ("python", "graph"),
            "external_library",
            "root_ordered",
            "runtime_ordered",
            "provider_owned",
            "existing_public",
            activation_mode="explicit_hardware_api",
            dependency_name="cuDSS",
            resource_effects=(
                "read:sparse_matrix",
                "read:rhs",
                "write:solution",
                "write:provider_workspace",
            ),
            lifetime_policy="provider_plan",
            update_policy="rebind",
            requirements=(
                "CUDA driver API >= 12.0",
                "bundled Forge cuDSS provider C ABI adapter",
                "user-managed cuDSS 0.8.x shared library",
                "compatible user-managed cuBLAS dependency",
            ),
            public_api=("ti.hardware.linalg.CudssPlan / CudssSolveRecording"),
            dtypes=("matrix:f32", "rhs:f32", "solution:f32"),
            shapes_or_tiles=("single square matrix", "single rhs"),
            layouts=("scalar CSR with i32 offsets and indices",),
            numeric_contracts=("analysis -> factorization -> solve",),
            notes=(
                "Explicit Python plan or root-Graph native solve; Taichi kernels are never rewritten to call cuDSS.",
                "The thin Forge adapter is bundled in the existing runtime wheel; the vendor runtime is user-managed and adds no Forge wheel variant.",
                "cuDSS is Preview, therefore execution is fail-closed outside the qualified 0.8.x ABI family.",
                "Graph replay re-records one runtime-ordered solve call; this is not CUDA stream capture and does not claim CUDA Graph serialization.",
            ),
        ),
        _operation(
            "linalg.solve.cudss_auto",
            "linalg.sparse_direct_solve",
            "cudss",
            ("cuda",),
            "lazy_external",
            "vendor_algorithm",
            "vendor_library",
            "implementation_defined",
            ("python",),
            "external_library",
            "unsupported",
            "runtime_ordered",
            "provider_owned",
            "existing_public",
            activation_mode="domain_api_auto_provider",
            dependency_name="cuDSS",
            resource_effects=(
                "read:sparse_matrix",
                "read:rhs",
                "write:solution",
                "write:provider_workspace",
            ),
            lifetime_policy="provider_plan",
            update_policy="rebind",
            requirements=(
                "CUDA driver API >= 12.0",
                "bundled Forge cuDSS provider C ABI adapter",
                "user-managed cuDSS 0.8.x matching CUDA 12 or CUDA 13",
                "compatible user-managed cuBLAS dependency",
            ),
            public_api=("ti.linalg.SparseSolver(provider='auto', provider_profile=profile)"),
            dtypes=("matrix:f32", "rhs:f32", "solution:f32"),
            shapes_or_tiles=("single square matrix", "single rhs"),
            layouts=("scalar CSR with i32 offsets and indices",),
            numeric_contracts=("analysis -> factorization -> solve",),
            notes=(
                "Automatic selection occurs only at SparseSolver analysis, never inside a Taichi kernel.",
                "Auto requires validated evidence matching the exact topology, device, runtime build, provider ABI/version, solver contract, and expected solve reuse.",
                "Without evidence auto does not probe or load optional cuDSS and retains the embedded cuSOLVERSp route.",
                "CUDA 11 and older, an absent or incompatible optional provider, f64, ineligible formats, scope mismatches, and failed cost admission retain cuSOLVERSp.",
                "Explicit provider='cudss' is capability-gated but never performance-gated; analysis, factorization, and numerical failures remain visible.",
            ),
        ),
        _operation(
            "linalg.refactor_solve.cudss",
            "linalg.sparse_direct_solve",
            "cudss",
            ("cuda",),
            "lazy_external",
            "vendor_algorithm",
            "vendor_library",
            "implementation_defined",
            ("python", "graph"),
            "external_library",
            "root_ordered",
            "runtime_ordered",
            "provider_owned",
            "existing_public",
            activation_mode="explicit_hardware_api",
            dependency_name="cuDSS",
            resource_effects=(
                "read:matrix_values",
                "read:rhs",
                "write:solution",
                "read_write:provider_factor_workspace",
            ),
            lifetime_policy="provider_plan",
            update_policy="rebind",
            requirements=(
                "CUDA driver API >= 12.0",
                "bundled Forge cuDSS provider C ABI adapter",
                "user-managed cuDSS 0.8.x shared library",
                "prior successful analysis and factorization",
            ),
            public_api=("ti.hardware.linalg.CudssPlan.record_refactor_solve"),
            dtypes=(
                "matrix_values:f32",
                "rhs:f32",
                "solution:f32",
            ),
            shapes_or_tiles=("fixed square CSR pattern", "single rhs"),
            layouts=(
                "compact explicit values matching plan nnz",
                "scalar CSR with i32 offsets and indices",
            ),
            numeric_contracts=(
                "every action invalidates old factors",
                "refactorization -> solve publishes one factor generation",
                "failure leaves factors invalid and skips standalone solve",
            ),
            notes=(
                "This is one root-Graph native action, never a kernel intrinsic or structured-control node.",
                "One plan permits at most one unretired refactorize+solve transaction; overlapping reuse fails closed.",
                "The values ndarray is read directly on device, so no host numeric-version inference is used.",
                "Provider installation remains user-managed and adds no Forge wheel variant.",
            ),
        ),
        _operation(
            "runtime.probe.cusparselt",
            "provider.runtime_probe",
            "cusparselt",
            ("cuda",),
            "lazy_external",
            "vendor_hardware_runtime",
            "vendor_hardware_runtime",
            "none",
            ("python",),
            "external_library",
            "unsupported",
            "explicit",
            "none",
            "internal_foundation",
            activation_mode="explicit_hardware_api",
            dependency_name="cuSPARSELt",
            lifetime_policy="call",
            update_policy="immutable",
            requirements=(
                "bundled Forge cuSPARSELt probe adapter",
                "user-managed cuSPARSELt 0.4.x through 0.9.x shared library",
            ),
            public_api="ti.hardware.probe('cusparselt', library_path=...)",
            notes=(
                "The probe audits the version and core execution symbols, then releases both adapter and vendor-runtime handles.",
                "No sparse MMA execution API, automatic provider route, Graph command, or kernel intrinsic is exposed yet.",
                "The vendor runtime remains optional and adds no Forge wheel variant.",
            ),
        ),
        _operation(
            "runtime.probe.cutensor",
            "provider.runtime_probe",
            "cutensor",
            ("cuda",),
            "lazy_external",
            "vendor_hardware_runtime",
            "vendor_hardware_runtime",
            "none",
            ("python",),
            "external_library",
            "unsupported",
            "explicit",
            "none",
            "internal_foundation",
            activation_mode="explicit_hardware_api",
            dependency_name="cuTENSOR",
            lifetime_policy="call",
            update_policy="immutable",
            requirements=(
                "bundled Forge cuTENSOR probe adapter",
                "user-managed cuTENSOR 2.0.x through 2.7.x shared library",
            ),
            public_api="ti.hardware.probe('cutensor', library_path=...)",
            notes=(
                "The probe audits the version and contraction/reduction symbol surface without creating a cuTENSOR handle.",
                "No contraction, reduction, Graph command, automatic provider route, or kernel intrinsic is exposed yet.",
                "The vendor runtime remains optional and adds no Forge wheel variant.",
            ),
        ),
        _operation(
            "runtime.probe.amgx",
            "provider.runtime_probe",
            "amgx",
            ("cuda",),
            "lazy_external",
            "vendor_hardware_runtime",
            "vendor_hardware_runtime",
            "none",
            ("python",),
            "external_library",
            "unsupported",
            "explicit",
            "none",
            "internal_foundation",
            activation_mode="explicit_hardware_api",
            dependency_name="AmgX",
            lifetime_policy="call",
            update_policy="immutable",
            requirements=(
                "bundled Forge AmgX stable-C-API probe adapter",
                "user-managed AmgX shared library and compatible CUDA dependencies",
            ),
            public_api="ti.hardware.probe('amgx', library_path=...)",
            notes=(
                "The probe audits the stable C API and version without calling AMGX_initialize or allocating solver resources.",
                "No setup/solve execution API, automatic provider route, Graph command, or kernel intrinsic is exposed yet.",
                "The vendor runtime remains optional and adds no Forge wheel variant; MPI remains outside this mount.",
            ),
        ),
    )


def reference_provider_operations(_operation):
    return (
        _operation(
            "algorithms.primitives.cub",
            "algorithms.primitives",
            "cub_reference",
            ("cuda",),
            "build_external",
            "vendor_algorithm",
            "vendor_library",
            "none",
            ("python", "graph"),
            "external_library",
            "root_ordered",
            "explicit",
            "caller_owned",
            "reference_only",
            activation_mode="explicit_hardware_api",
            dependency_name="CCCL/CUB",
            resource_effects=("read:input", "write:output", "write:workspace"),
            lifetime_policy="call",
            update_policy="per_dispatch",
            requirements=("CUB/CCCL headers", "CUDA device compiler", "CUDART"),
            public_api="ti.algorithms",
            notes=("disabled in official wheel builds",),
        ),
    )


__all__ = (
    "d1_provider_operations",
    "reference_provider_operations",
)
