"""Vulkan command and interop capability catalog fragments."""


def vulkan_command_operations(_operation):
    return (
        _operation(
            "runtime.buffer_commands.vulkan",
            "runtime.buffer_commands",
            "vulkan_rhi",
            ("vulkan",),
            "core",
            "compute_native",
            "native_command",
            "qualified",
            ("python", "graph"),
            "native_command",
            "root_ordered",
            "runtime_ordered",
            "none",
            "existing_public",
            activation_mode="explicit_hardware_api",
            resource_effects=("read:source_buffers", "write:destination_buffers"),
            lifetime_policy="runtime_generation",
            update_policy="rebind",
            requirements=("Vulkan RHI command list",),
            public_api="ti.graph.VulkanBufferCommandRecording",
            notes=("low-level substrate; not a RasterPass or AS provider",),
        ),
        _operation(
            "image.copy.vulkan",
            "image.copy",
            "vulkan_rhi",
            ("vulkan",),
            "core",
            "compute_native",
            "native_command",
            "implementation_defined",
            ("python", "graph"),
            "native_command",
            "root_ordered",
            "runtime_ordered",
            "none",
            "existing_public",
            activation_mode="explicit_hardware_api",
            resource_effects=(
                "read:source_image_or_buffer",
                "write:destination_image_or_buffer",
            ),
            lifetime_policy="runtime_generation",
            update_policy="rebind",
            layouts=(
                "whole/region color image",
                "buffer-image row length/image height/byte offset",
                "base mip/layer descriptor with current Texture admission",
            ),
            requirements=(
                "Vulkan RHI copy-image and buffer-image paths",
                "format-feature-qualified blit",
            ),
            public_api="ti.hardware.image transfer recordings",
            notes=(
                "This is a native device image command, but Vulkan does not promise "
                "which physical engine executes the copy; it is not labeled "
                "dedicated-hardware acceleration.",
                "Image copy requires matching formats; region extents may differ "
                "for blit only. Depth/stencil and aliases are rejected.",
                "Current Texture resources expose one mip and one layer; descriptors "
                "carry subresource identity and fail closed for unsupported slices.",
            ),
        ),
        _operation(
            "raster.draw.vulkan",
            "raster.draw",
            "vulkan_graphics",
            ("vulkan",),
            "core",
            "fixed_function",
            "fixed_function",
            "qualified",
            ("python", "graph"),
            "native_command",
            "root_ordered",
            "runtime_ordered",
            "provider_owned",
            "existing_public",
            activation_mode="explicit_hardware_api",
            resource_effects=(
                "read:geometry_and_uniform_buffers",
                "read:optional_indirect_command_and_count_buffers",
                "read_write:storage_buffers",
                "write_or_read_write:color_depth_attachments",
            ),
            lifetime_policy="resource_generation",
            update_policy="immutable",
            dtypes=(
                "vertex:declared BufferFormat",
                "index:u32",
                "indirect_command:u32",
                "indirect_count:u32",
                "shader:uniform_or_storage_ndarray",
                "color:attachment format",
                "depth:depth32f",
            ),
            shapes_or_tiles=("2D offscreen target",),
            layouts=(
                "declared vertex bindings and attributes",
                "optional uint32 index buffer",
                "explicit uniform/storage descriptor buffers",
                "one color and optional depth attachment with clear/load and store",
                "one or more draws recorded into one render pass",
                "fixed-count or feature-gated count-buffer indirect draws",
            ),
            numeric_contracts=(
                "depth:test_and_write",
                "color:rgba_offscreen",
            ),
            deterministic=False,
            requirements=(
                "Vulkan RHI graphics pipeline and graphics queue",
                "caller-provided SPIR-V vertex and fragment shaders",
                "indirect buffers follow VkDrawIndirectCommand or VkDrawIndexedIndirectCommand ABI",
            ),
            public_api="ti.hardware.graphics.VulkanGraphicsPipeline",
            notes=(
                "Explicit direct or root-Graph native command; kernel calls are impossible.",
                "This interface owns no renderer semantics: the caller supplies shaders, raw vertex/index buffers, attachments, draw ranges, and scheduling policy.",
                "VulkanGraphicsPassRecording batches N draws into one backend pass action; the legacy single-draw API is a compatibility wrapper.",
                "Compute-to-graphics-to-compute ordering uses backend semaphores and does not add a host wait.",
                "Indirect draws consume kernel-produced command/count ndarrays without host readback; declared geometry bounds are validated conservatively.",
                "Fixed-count indirect is baseline Vulkan; multi-draw, nonzero firstInstance, and count-buffer variants are admitted from active-device feature facts.",
            ),
        ),
        _operation(
            "raster.adapter.ggui.vulkan",
            "raster.adapter",
            "vulkan_raster",
            ("vulkan",),
            "core",
            "fixed_function",
            "fixed_function",
            "qualified",
            ("python", "graph"),
            "native_command",
            "opaque",
            "runtime_ordered",
            "provider_owned",
            "existing_public",
            activation_mode="explicit_hardware_api",
            resource_effects=("read:geometry", "write:hidden_color_depth"),
            lifetime_policy="resource_generation",
            update_policy="immutable",
            dtypes=("vertex:f32", "index:i32", "color:f32"),
            shapes_or_tiles=("2D offscreen target",),
            layouts=("mesh", "mesh_instance", "particles", "lines"),
            deterministic=False,
            requirements=(
                "Vulkan graphics pipeline",
                "GGUI built-in raster shaders",
            ),
            public_api="ti.hardware.raster.RasterPass",
            notes=(
                "Compatibility and qualification adapter only; direct Python and explicit segmented root-Graph execution are supported.",
                "Its GGUI scene semantics and hidden attachments are not the Forge low-level graphics abstraction.",
            ),
        ),
    )


def vulkan_interop_operations(_operation):
    return (
        _operation(
            "interop.external_buffer.cuda_vulkan",
            "runtime.interop",
            "cuda_vulkan_interop",
            ("cuda", "vulkan"),
            "core",
            "runtime_interop",
            "native_command",
            "implementation_defined",
            ("python", "graph"),
            "native_command",
            "root_ordered",
            "explicit",
            "caller_owned",
            "existing_public",
            activation_mode="explicit_hardware_api",
            resource_effects=("read_write:external_buffer",),
            lifetime_policy="resource_generation",
            update_policy="rebind",
            requirements=(
                "matching device UUID",
                "external memory",
                "external semaphore",
            ),
            public_api="ti.interop",
        ),
    )


def vulkan_future_operations(_operation):
    return (
        _operation(
            "internal.raster.mesh_shader.vulkan",
            "raster.geometry_frontend",
            "vulkan_mesh_shader",
            ("vulkan",),
            "core",
            "compute_native",
            "native_shader_operation",
            "none",
            ("internal",),
            "native_command",
            "backend_recorded",
            "runtime_ordered",
            "graph_owned",
            "planned",
            activation_mode="compiler_automatic",
            resource_effects=("read:geometry", "write:raster_primitives"),
            lifetime_policy="graph_generation",
            update_policy="rebind",
            requirements=(
                "VK_EXT_mesh_shader feature query and device enablement",
                "SPV_EXT_mesh_shader code generation",
                "mesh pipeline and vkCmdDrawMeshTasksEXT recording",
            ),
            notes=(
                "Raster provider specialization; not a public shader model",
                "Vulkan headers alone do not constitute an implemented provider",
            ),
        ),
    )


__all__ = (
    "vulkan_command_operations",
    "vulkan_interop_operations",
    "vulkan_future_operations",
)
