"""External D1 provider capability catalog fragments."""

def d1_provider_operations(_operation):
    return (
        _operation(
            "linalg.gemm.cublas",
            "linalg.gemm",
            "cublas",
            ("cuda",),
            "lazy_external",
            "vendor_algorithm",
            "vendor_library",
            "implementation_defined",
            ("python", "graph"),
            "external_library",
            "recordable",
            "explicit",
            "none",
            "existing_public",
            activation_mode="explicit_hardware_api",
            dependency_name="cuBLAS",
            resource_effects=("read:inputs", "read_write:output"),
            lifetime_policy="runtime_generation",
            update_policy="per_dispatch",
            requirements=("compatible cuBLAS shared library",),
            public_api="ti.hardware.linalg.gemm_f32",
            dtypes=("input:f32", "output:f32"),
            layouts=("compact row-major 2D",),
            numeric_contracts=("C = alpha * A @ B + beta * C",),
            notes=(
                "Explicit Python or root-Graph vendor-library command.",
                "The first execution lazy-loads the user's compatible cuBLAS shared library and retains one handle per Program.",
                "Ordinary matrix multiplication and Taichi kernels are never rewritten to call this provider.",
            ),
        ),
        _operation(
            "linalg.spmv.cusparse",
            "linalg.spmv",
            "cusparse",
            ("cuda",),
            "lazy_external",
            "vendor_algorithm",
            "vendor_library",
            "implementation_defined",
            ("python",),
            "external_library",
            "unsupported",
            "runtime_ordered",
            "provider_owned",
            "existing_public",
            activation_mode="domain_api_auto_provider",
            dependency_name="cuSPARSE",
            resource_effects=("read:sparse_matrix", "read:input", "write:output"),
            lifetime_policy="resource_generation",
            update_policy="rebind",
            requirements=("compatible cuSPARSE shared library",),
            public_api="ti.linalg.SparseMatrix.__matmul__",
            dtypes=("matrix:f32", "input:f32", "output:f32"),
            layouts=("scalar CSR", "fixed-block BSR when provider supports it"),
            numeric_contracts=("output = sparse_matrix @ input",),
            notes=(
                "The public sparse-matrix domain API considers cuSPARSE automatically on CUDA; users do not call a ti.hardware command.",
                "Without stable matrix-scoped cost evidence, auto fails closed to the embedded CUDA CSR/BSR kernel route.",
                "Admission scopes rows, columns, nnz, format, provider version, reuse, transfer/conversion cost, warmup, sample count, CV, and order drift.",
                "CSR SpMV caches matrix/vector descriptors, workspace, and optional provider preprocessing for repeated calls.",
                "The current stored SparseMatrix route is direct Python execution and is not a recordable Graph action.",
            ),
        ),
        _operation(
            "linalg.spmv.cusparse_explicit",
            "linalg.spmv",
            "cusparse",
            ("cuda",),
            "lazy_external",
            "vendor_algorithm",
            "vendor_library",
            "implementation_defined",
            ("python", "graph"),
            "external_library",
            "recordable",
            "runtime_ordered",
            "provider_owned",
            "existing_public",
            activation_mode="explicit_hardware_api",
            dependency_name="cuSPARSE",
            resource_effects=("read:sparse_matrix", "read:input", "write:output"),
            lifetime_policy="resource_generation",
            update_policy="rebind",
            requirements=("compatible cuSPARSE shared library",),
            public_api="ti.hardware.linalg.spmv_f32",
            dtypes=("matrix:f32", "input:f32", "output:f32"),
            layouts=("scalar CSR", "fixed-block BSR when provider supports it"),
            numeric_contracts=("output = sparse_matrix @ input",),
            notes=(
                "Explicit Python or root-Graph command over an existing CUDA SparseMatrix.",
                "The recording holds the matrix generation alive and reuses its cuSPARSE handle, descriptors, workspace, and optional preprocessing.",
                "This manual hardware interface is separate from the automatic SparseMatrix @ ndarray domain route.",
            ),
        ),
        _operation(
            "linalg.solve.cusolver",
            "linalg.solve",
            "cusolver",
            ("cuda",),
            "lazy_external",
            "vendor_algorithm",
            "vendor_library",
            "implementation_defined",
            ("python",),
            "external_library",
            "unsupported",
            "runtime_ordered",
            "provider_owned",
            "existing_public",
            activation_mode="domain_api_auto_provider",
            dependency_name="cuSOLVER",
            resource_effects=("read:system", "write:solution", "write:workspace"),
            lifetime_policy="provider_plan",
            update_policy="rebind",
            requirements=(
                "compatible cuSOLVER shared library",
                "compatible cuSPARSE shared library",
            ),
            public_api="ti.linalg.SparseSolver",
            dtypes=("matrix:f32", "rhs:f32", "solution:f32"),
            layouts=("scalar CSR",),
            numeric_contracts=(
                "LLT/LDLT use the cuSOLVER sparse Cholesky path",
                "LU uses the host-assisted cuSOLVER sparse LU path",
            ),
            notes=(
                "SparseSolver selects this provider automatically when constructed on CUDA; it is not a ti.hardware command.",
                "Pattern analysis, numeric factorization, and solve are explicit domain-API stages and are not Graph-recordable.",
                "CUDA LU includes device-host transfers; the Cholesky solve remains device-resident after setup.",
            ),
        ),
        _operation(
            "fft.transform.cufft",
            "fft.transform",
            "cufft",
            ("cuda",),
            "lazy_external",
            "vendor_algorithm",
            "vendor_library",
            "implementation_defined",
            ("python", "graph"),
            "external_library",
            "recordable",
            "runtime_ordered",
            "provider_owned",
            "existing_public",
            activation_mode="explicit_hardware_api",
            dependency_name="cuFFT",
            resource_effects=("read:input", "write:output", "write:workspace"),
            lifetime_policy="provider_plan",
            update_policy="rebind",
            requirements=("compatible cuFFT shared library",),
            public_api="ti.hardware.fft.CufftPlan1D / CufftPlanND",
            dtypes=("real:f32", "complex-pair:f32"),
            shapes_or_tiles=(
                "C2C:(length,2) or (batch,length,2)",
                "R2C:real length to Hermitian length//2+1",
                "C2R:Hermitian length//2+1 to real length",
                "CufftPlanND:batched rank-2/rank-3",
            ),
            layouts=(
                "compact out-of-place C2C/R2C/C2R",
                "explicit embed/element-stride/batch-distance",
            ),
            numeric_contracts=(
                "forward sign:-1",
                "inverse sign:+1 unnormalized",
                "inverse_scale:1/length",
            ),
            notes=(
                "Callbacks, LTO, multi-GPU, and independently arbitrary per-axis strides are excluded.",
                "Identical plan descriptors reuse a runtime-generation cuFFT plan; workspace bytes are queried from cuFFT.",
            ),
        ),
    )


def reference_provider_operations(_operation):
    return (
        _operation(
            "algorithms.primitives.cub",
            "algorithms.primitives",
            "cub_reference",
            ("cuda",),
            "build_external",
            "vendor_algorithm",
            "vendor_library",
            "none",
            ("python", "graph"),
            "external_library",
            "recordable",
            "explicit",
            "caller_owned",
            "reference_only",
            activation_mode="explicit_hardware_api",
            dependency_name="CCCL/CUB",
            resource_effects=("read:input", "write:output", "write:workspace"),
            lifetime_policy="call",
            update_policy="per_dispatch",
            requirements=("CUB/CCCL headers", "CUDA device compiler", "CUDART"),
            public_api="ti.algorithms",
            notes=("disabled in official wheel builds",),
        ),
    )


__all__ = (
    "d1_provider_operations",
    "reference_provider_operations",
)
