"""Kernel-inline and compiler-internal capability catalog fragments."""

def kernel_intrinsic_operations(_operation):
    return (
        _operation(
            "sampling.texture.vulkan",
            "sampling.texture",
            "vulkan_texture",
            ("vulkan",),
            "core",
            "fixed_function",
            "native_shader_operation",
            "qualified",
            ("kernel",),
            "kernel_intrinsic",
            "inline",
            "runtime_ordered",
            "none",
            "existing_public",
            activation_mode="explicit_kernel_intrinsic",
            resource_effects=("read:texture",),
            lifetime_policy="runtime_generation",
            update_policy="immutable",
            dtypes=(
                "sampled:f32",
                "storage:f32",
                "storage:i32",
                "storage:u32",
            ),
            shapes_or_tiles=("1D", "2D", "3D"),
            layouts=("sampled_image", "storage_image"),
            numeric_contracts=(
                "sample_lod:explicit_lod_vec4_f32",
                "fetch:texel_vec4_f32",
                "storage_load_store:format_sampled_type",
            ),
            deterministic=False,
            requirements=(
                "SPIR-V OpImageSampleExplicitLod and OpImageFetch",
                "Vulkan combined image sampler",
            ),
            public_api="ti.Texture(..., sampler=ti.hardware.sampling.SamplerConfig(...))",
            notes=(
                "sample_lod uses immutable per-texture min/mag filter and U/V/W "
                "address modes; Vulkan sampler objects are cached per device.",
                "The current one-mip contract uses normalized coordinates and exposes no anisotropy or comparison mode.",
                "fetch uses integer texel coordinates and ignores sampler configuration.",
            ),
        ),
        _operation(
            "sampling.texture.cuda",
            "sampling.texture",
            "cuda_texture",
            ("cuda",),
            "core",
            "hardware_intrinsic",
            "native_shader_operation",
            "implementation_defined",
            ("kernel",),
            "kernel_intrinsic",
            "inline",
            "current",
            "none",
            "planned",
            activation_mode="explicit_kernel_intrinsic",
            resource_effects=("read:texture",),
            lifetime_policy="runtime_generation",
            update_policy="immutable",
            requirements=(
                "LLVM/CUDA Program texture resource allocation and lifetime",
                "CUDA array plus texture-object creation and upload",
                "CUDA texture kernel-argument ABI",
                "LLVM TextureOpStmt lowering",
            ),
            public_api="ti.Texture",
            notes=(
                "Texture resources are currently allocated only by the GFX Program; the LLVM/CUDA Program returns a null texture allocation.",
                "LLVM CUDA TextureOp lowering is not implemented, so hardware presence alone cannot admit this route.",
            ),
        ),
        _operation(
            "kernel.atomic.cuda",
            "kernel.atomic",
            "cuda_atomic",
            ("cuda",),
            "core",
            "hardware_intrinsic",
            "hardware_instruction",
            "implementation_defined",
            ("kernel",),
            "kernel_intrinsic",
            "inline",
            "runtime_ordered",
            "none",
            "existing_public",
            activation_mode="explicit_kernel_intrinsic",
            resource_effects=("read_write:target",),
            lifetime_policy="runtime_generation",
            update_policy="per_dispatch",
            dtypes=("integer operation-dependent", "f16/f32/f64 operation-dependent"),
            numeric_contracts=("returns old value and atomically publishes the update",),
            requirements=("supported CUDA dtype/operation/device combination",),
            public_api="ti.atomic_*",
            notes=(
                "An explicit atomic call or parallel global augmented assignment is lowered inside the kernel; it is not a Python hardware command.",
                "The backend may use a native atomic instruction or an atomic-CAS implementation depending on dtype, operation, and target.",
            ),
        ),
        _operation(
            "kernel.atomic.vulkan",
            "kernel.atomic",
            "vulkan_atomic",
            ("vulkan",),
            "core",
            "hardware_intrinsic",
            "native_shader_operation",
            "implementation_defined",
            ("kernel",),
            "kernel_intrinsic",
            "inline",
            "runtime_ordered",
            "none",
            "existing_public",
            activation_mode="explicit_kernel_intrinsic",
            resource_effects=("read_write:target",),
            lifetime_policy="runtime_generation",
            update_policy="per_dispatch",
            dtypes=("integer operation-dependent", "f32/f64 capability-dependent"),
            numeric_contracts=("returns old value and atomically publishes the update",),
            requirements=("supported SPIR-V atomic dtype/operation/device capability",),
            public_api="ti.atomic_*",
            notes=(
                "Explicit atomic semantics are lowered to SPIR-V atomic operations or capability-gated CAS implementations.",
                "This is kernel-inline lowering, not a separately dispatched native executable.",
            ),
        ),
        _operation(
            "kernel.simt.warp.cuda",
            "kernel.simt.warp",
            "cuda_warp",
            ("cuda",),
            "core",
            "hardware_intrinsic",
            "hardware_instruction",
            "implementation_defined",
            ("kernel",),
            "kernel_intrinsic",
            "inline",
            "runtime_ordered",
            "none",
            "existing_public",
            activation_mode="explicit_kernel_intrinsic",
            lifetime_policy="runtime_generation",
            update_policy="immutable",
            dtypes=("i32", "u32 mask", "f32 shuffle"),
            shapes_or_tiles=("warp:32 lanes",),
            requirements=("CUDA warp execution", "match operations require compute capability >= 7.0"),
            public_api="ti.simt.warp",
            notes=(
                "User-written kernel intrinsics expose vote, ballot, shuffle, active-mask, match, and warp synchronization operations.",
            ),
        ),
        _operation(
            "kernel.simt.subgroup.vulkan",
            "kernel.simt.subgroup",
            "vulkan_subgroup",
            ("vulkan",),
            "core",
            "hardware_intrinsic",
            "native_shader_operation",
            "implementation_defined",
            ("kernel",),
            "kernel_intrinsic",
            "inline",
            "runtime_ordered",
            "none",
            "existing_public",
            activation_mode="explicit_kernel_intrinsic",
            lifetime_policy="runtime_generation",
            update_policy="immutable",
            dtypes=("i32/u32", "f32 capability-dependent"),
            shapes_or_tiles=("device subgroup size",),
            requirements=("matching Vulkan subgroup capability for each operation",),
            public_api="ti.simt.subgroup",
            notes=(
                "Qualified operations include barrier/elect, broadcast, size/id, reductions, inclusive scans, and shuffle/up/down.",
                "all/any/equal, broadcast-first, exclusive scans, and shuffle-xor fail closed because no lowering is registered.",
            ),
        ),
        _operation(
            "kernel.shared_memory.cuda_vulkan",
            "kernel.shared_memory",
            "gpu_shared_memory",
            ("cuda", "vulkan"),
            "core",
            "hardware_intrinsic",
            "hardware_instruction",
            "implementation_defined",
            ("kernel",),
            "kernel_intrinsic",
            "inline",
            "runtime_ordered",
            "none",
            "existing_public",
            activation_mode="explicit_kernel_intrinsic",
            resource_effects=("read_write:block_local_storage",),
            lifetime_policy="runtime_generation",
            update_policy="immutable",
            dtypes=("primitive", "fixed-shape tensor element"),
            layouts=("compile-time fixed per-block SharedArray",),
            requirements=("parallel range-for scope", "device shared-memory capacity"),
            public_api="ti.simt.block.SharedArray",
            notes=(
                "The user explicitly declares block-local storage and synchronization inside a kernel; allocation is per workgroup and cannot escape its offloaded loop.",
            ),
        ),
        _operation(
            "kernel.block_local.cuda",
            "kernel.block_local_cache",
            "cuda_bls",
            ("cuda",),
            "core",
            "hardware_intrinsic",
            "compute_kernel",
            "implementation_defined",
            ("kernel",),
            "kernel_intrinsic",
            "inline",
            "runtime_ordered",
            "none",
            "existing_public",
            activation_mode="explicit_kernel_intrinsic",
            resource_effects=("read_write:block_local_cache",),
            lifetime_policy="runtime_generation",
            update_policy="per_dispatch",
            requirements=("ti.extension.bls", "supported SNode access pattern"),
            public_api="ti.block_local",
            notes=(
                "This explicit compiler hint lowers admitted field tiles into block-local storage; the current qualified slice covers supported gather/read-cache access patterns.",
                "Sparse SNode scatter/write-back automatically retains the ordinary global store/atomic path because a whole-pad BLS epilogue is not semantics-preserving.",
                "The separate internal.tile.async.cuda descriptor reports when an admitted read-only copy is further specialized to cp.async.",
            ),
        ),
        _operation(
            "internal.reduction.grouped.cuda_vulkan",
            "kernel.reduction",
            "gpu_grouped_reduction",
            ("cuda", "vulkan"),
            "core",
            "compute_native",
            "compute_kernel",
            "implementation_defined",
            ("internal",),
            "kernel_intrinsic",
            "inline",
            "runtime_ordered",
            "none",
            "existing_internal",
            activation_mode="compiler_automatic",
            resource_effects=("read:lane_values", "atomic:destination",),
            lifetime_policy="runtime_generation",
            update_policy="per_dispatch",
            requirements=("compiler-recognized reduction", "matching device group capability"),
            notes=(
                "Automatic compiler selection aggregates recognized reductions within a CUDA block or Vulkan subgroup before publishing fewer global atomics.",
                "User atomic semantics remain unchanged, and unsupported patterns retain the ordinary atomic path.",
            ),
        ),
        _operation(
            "internal.listgen.subgroup_ballot.vulkan",
            "runtime.list_generation",
            "vulkan_subgroup_listgen",
            ("vulkan",),
            "core",
            "hardware_intrinsic",
            "native_shader_operation",
            "implementation_defined",
            ("internal",),
            "kernel_intrinsic",
            "inline",
            "runtime_ordered",
            "none",
            "existing_internal",
            activation_mode="compiler_automatic",
            resource_effects=("read:active_lanes", "atomic:list_counter", "write:list_entries"),
            lifetime_policy="runtime_generation",
            update_policy="per_dispatch",
            requirements=("spirv_has_subgroup_ballot", "spirv_listgen_subgroup_ballot enabled"),
            notes=(
                "Automatic internal lowering lets one elected lane reserve a contiguous list range per subgroup and broadcasts the base to active lanes.",
                "The legacy per-active-lane atomic path remains the fail-closed fallback.",
            ),
        ),
        _operation(
            "matrix.mma.cuda",
            "matrix.mma",
            "cuda_matrix",
            ("cuda",),
            "core",
            "hardware_intrinsic",
            "hardware_instruction",
            "qualified",
            ("python", "graph"),
            "native_command",
            "root_ordered",
            "runtime_ordered",
            "none",
            "existing_public",
            activation_mode="explicit_hardware_api",
            resource_effects=("read:a", "read:b", "write:output"),
            lifetime_policy="runtime_generation",
            update_policy="rebind",
            dtypes=("a:f16", "b:f16", "accumulator:f32", "output:f32"),
            shapes_or_tiles=("m16n16k16", "compact batch"),
            layouts=("row_major_a", "row_major_b", "row_major_output"),
            numeric_contracts=("output=A*B", "f16_inputs:f32_accumulate"),
            deterministic=False,
            requirements=(
                "NVIDIA compute capability >= 7.0",
                "PTX ISA >= 6.3",
                "warp size 32",
                "32-byte aligned compact buffers",
            ),
            public_api="ti.hardware.matrix.mma_f16_f32",
            notes=(
                "Explicit Driver/PTX native command; ordinary ti.Matrix matmul is "
                "not rewritten and kernel calls remain unsupported.",
                "No CUDA Toolkit runtime or vendor algorithm package is required.",
            ),
        ),
        _operation(
            "matrix.mma.vulkan",
            "matrix.mma",
            "vulkan_matrix",
            ("vulkan",),
            "core",
            "hardware_intrinsic",
            "native_shader_operation",
            "implementation_defined",
            ("kernel",),
            "kernel_intrinsic",
            "inline",
            "runtime_ordered",
            "none",
            "planned",
            activation_mode="explicit_kernel_intrinsic",
            lifetime_policy="runtime_generation",
            update_policy="immutable",
            requirements=(
                "VK_KHR_cooperative_matrix feature query and device enablement",
                "vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR tuple enumeration",
                "opaque cooperative-matrix tile type and typed kernel IR",
                "SPV_KHR_cooperative_matrix load/mul-add/store lowering",
            ),
            public_api="ti.hardware.matrix",
            notes=(
                "The repository has no Vulkan cooperative-matrix feature, type, IR, or code-generation chain yet.",
                "Supported M/N/K, component types, scope, layout, and saturation must come from device properties rather than copying the CUDA m16n16k16 contract.",
            ),
        ),
    )


def kernel_internal_operations(_operation):
    return (
        _operation(
            "internal.tile.async.cuda",
            "tile.async",
            "cuda_async_tile",
            ("cuda",),
            "core",
            "hardware_intrinsic",
            "hardware_instruction",
            "qualified",
            ("internal",),
            "kernel_intrinsic",
            "inline",
            "current",
            "none",
            "existing_internal",
            activation_mode="compiler_automatic",
            dtypes=("i32", "u32", "f32", "i64", "u64", "f64"),
            shapes_or_tiles=("compiler-generated struct-for BLS >= 8192 bytes",),
            lifetime_policy="runtime_generation",
            update_policy="immutable",
            requirements=(
                "PTX ISA >= 7.0",
                "CUDA compute capability >= 8.0",
                "direct 4/8/16-byte global-to-BLS compiler copy",
                "read-only BLS with no write-back epilogue",
            ),
            notes=(
                "transparent compiler specialization; no public cp.async or TMA API",
                "smaller or non-admitted prologues retain synchronous lowering",
            ),
        ),
    )


__all__ = (
    "kernel_intrinsic_operations",
    "kernel_internal_operations",
)
