"""Public Vulkan hardware ray-query provider API."""

from taichi_forge.hardware._vulkan_micromap import VulkanOpacityMicromap

from taichi_forge.hardware._ray import (
    InstanceTLAS,
    RayInstance,
    TriangleBLAS,
    TriangleScene,
    VulkanBLASBuildRecording,
    VulkanBLASRefitRecording,
    VulkanRayQueryRecording,
    VulkanRayRefitRecording,
    VulkanTLASBuildRecording,
    VulkanTLASRefitRecording,
    VulkanTLASTransformRecording,
    is_available,
    is_opacity_micromap_available,
)
from taichi_forge.hardware._optix import (
    OptixAlphaMask,
    OptixOpacityMicromap,
    OptixGASRefitRecording,
    OptixInstanceRefitRecording,
    OptixInstanceScene,
    OptixProvider,
    OptixRayInstance,
    OptixRayQueryRecording,
    OptixRayRefitRecording,
    OptixTriangleScene,
    OptixTriangleGAS,
    is_loaded as is_optix_loaded,
    load_provider as load_optix_provider,
)

__all__ = [
    "is_opacity_micromap_available",
    "VulkanOpacityMicromap",
    "InstanceTLAS",
    "OptixAlphaMask",
    "OptixOpacityMicromap",
    "OptixGASRefitRecording",
    "OptixInstanceRefitRecording",
    "OptixInstanceScene",
    "OptixProvider",
    "OptixRayInstance",
    "OptixRayQueryRecording",
    "OptixRayRefitRecording",
    "OptixTriangleScene",
    "OptixTriangleGAS",
    "RayInstance",
    "TriangleBLAS",
    "TriangleScene",
    "VulkanBLASBuildRecording",
    "VulkanBLASRefitRecording",
    "VulkanRayQueryRecording",
    "VulkanRayRefitRecording",
    "VulkanTLASBuildRecording",
    "VulkanTLASRefitRecording",
    "VulkanTLASTransformRecording",
    "is_available",
    "is_optix_loaded",
    "load_optix_provider",
]
