#!/usr/bin/env python3
"""Generate the checked-in, Toolkit-free CUDA primitive PTX header."""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import re
import subprocess
import tempfile

SUFFIXES = ("i32", "u32", "f32", "i64", "u64", "f64")
REQUIRED_ENTRIES = (
    *(f"scan_blocks_{suffix}" for suffix in SUFFIXES),
    *(f"scan_tiles_{suffix}" for suffix in SUFFIXES),
    *(f"uniform_add_{suffix}" for suffix in SUFFIXES),
    *(f"reduce_blocks_{suffix}" for suffix in SUFFIXES),
    "zero_bins_i32",
    "zero_bins_i64",
    "histogram_i32_i32",
    "histogram_u32_i32",
    "histogram_i32_i64",
    "histogram_u32_i64",
    *(f"add_strided_{suffix}" for suffix in SUFFIXES),
    "add_scaled_strided_f32",
    "add_scaled_strided_f64",
    "gather_add_strided_f32",
    "gather_add_strided_f64",
    "sparse_diagonal_apply_f32",
    "sparse_diagonal_refresh_f32",
    "sparse_block_diagonal_apply_f32",
    *(f"scatter_add_strided_{suffix}" for suffix in SUFFIXES),
    *(f"zero_strided_{suffix}" for suffix in SUFFIXES),
    "compact_rank_tiles_i32",
    "compact_scatter_tiled_words",
    "copy_i32_strided",
    "bucket_scatter_words",
    *(f"radix_init_{suffix}" for suffix in SUFFIXES),
    "radix_rank4_u32",
    "radix_rank4_u64",
    "radix_hist_scan",
    "radix_hist_uniform",
    "radix_digit_bases",
    "radix_scatter4_u32",
    "radix_scatter4_u64",
    "radix_gather_words",
    "radix_copy_words",
    "sparse_assembly_pack_validate",
    "sparse_assembly_pack_packed_validate",
    "sparse_assembly_mark_segments",
    "sparse_assembly_scatter_segments",
    "sparse_assembly_reduce_segments",
    "sparse_assembly_emit_csr",
    "sparse_assembly_finalize_control",
)


def validate_ptx(ptx: str) -> None:
    version = re.search(r"(?m)^\.version\s+(\d+)\.(\d+)\s*$", ptx)
    target = re.search(r"(?m)^\.target\s+sm_(\d+)\s*$", ptx)
    if version is None or tuple(map(int, version.groups())) > (6, 0):
        raise RuntimeError("primitive PTX must use ISA 6.0 or older")
    if target is None or int(target.group(1)) > 50:
        raise RuntimeError("primitive PTX must target sm_50 or older")
    if ".extern .func" in ptx or "__nvvm_" in ptx:
        raise RuntimeError("primitive PTX contains an unresolved device symbol")
    missing = [
        entry for entry in REQUIRED_ENTRIES if re.search(rf"(?m)^\.visible \.entry {re.escape(entry)}\(", ptx) is None
    ]
    if missing:
        raise RuntimeError(f"primitive PTX is missing entries: {', '.join(missing)}")


def render_header(ptx: str, source: pathlib.Path) -> str:
    digest = hashlib.sha256(ptx.encode("utf-8")).hexdigest()
    chunk_size = 8192
    literals = "\n".join(
        f'R"taichi_cuda_ptx({ptx[start : start + chunk_size]})taichi_cuda_ptx"'
        for start in range(0, len(ptx), chunk_size)
    )
    return f"""// Generated by scripts/generate_cuda_primitive_ptx.py.
// Source: {source.as_posix()}
// PTX SHA256: {digest}
// Do not edit this file directly.
#pragma once

namespace taichi::lang::cuda {{

inline constexpr char kCudaHierarchicalPtx[] =
{literals};

}}  // namespace taichi::lang::cuda
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--clang", required=True, type=pathlib.Path)
    parser.add_argument(
        "--source",
        type=pathlib.Path,
        default=pathlib.Path("taichi/rhi/cuda/primitives/ptx/hierarchical.cu"),
    )
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=pathlib.Path("taichi/rhi/cuda/primitives/ptx/hierarchical_ptx.inc.h"),
    )
    args = parser.parse_args()

    source = args.source.resolve()
    output = args.output.resolve()
    if not args.clang.is_file():
        raise FileNotFoundError(f"Clang executable not found: {args.clang}")
    if not source.is_file():
        raise FileNotFoundError(f"CUDA primitive source not found: {source}")

    help_result = subprocess.run(
        [str(args.clang), "--help"],
        check=True,
        capture_output=True,
        text=True,
    )
    supports_ptx_feature = "--cuda-feature" in (
        help_result.stdout + help_result.stderr
    )
    ptx_feature = ["--cuda-feature=+ptx40"] if supports_ptx_feature else []

    with tempfile.TemporaryDirectory(prefix="taichi-cuda-primitive-ptx-") as tmp:
        ptx_path = pathlib.Path(tmp) / "hierarchical.ptx"
        subprocess.run(
            [
                str(args.clang),
                "-O3",
                "-std=c++17",
                "-x",
                "cuda",
                "--cuda-device-only",
                "-nocudainc",
                "-nocudalib",
                "--cuda-gpu-arch=sm_50",
                *ptx_feature,
                "-S",
                str(source),
                "-o",
                str(ptx_path),
            ],
            check=True,
        )
        ptx = ptx_path.read_text(encoding="utf-8")
        had_final_newline = ptx.endswith("\n")
        ptx = "\n".join(line.rstrip() for line in ptx.splitlines())
        if had_final_newline:
            ptx += "\n"

    validate_ptx(ptx)
    rendered = render_header(ptx, args.source)
    output.parent.mkdir(parents=True, exist_ok=True)
    if output.exists() and output.read_text(encoding="utf-8") == rendered:
        return
    output.write_text(rendered, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
