include_guard(GLOBAL)

# Usage requirements propagate through OBJECT libraries, but their object files
# do not. Link the transitive object closure when constructing a native binary.
function(ti_link_object_dependencies target root)
  set(pending ${root})
  set(visited)
  while(pending)
    list(POP_FRONT pending dependency)
    if(NOT TARGET ${dependency} OR dependency IN_LIST visited)
      continue()
    endif()
    list(APPEND visited ${dependency})
    get_target_property(kind ${dependency} TYPE)
    if(kind STREQUAL "OBJECT_LIBRARY" AND NOT dependency STREQUAL root)
      target_link_libraries(${target} PRIVATE ${dependency})
    endif()
    get_target_property(children ${dependency} LINK_LIBRARIES)
    if(children)
      foreach(child IN LISTS children)
        if(TARGET ${child})
          list(APPEND pending ${child})
        endif()
      endforeach()
    endif()
  endwhile()
endfunction()
